### ISSUE TITLE
Negative axis section is missing

### ISSUE THREAD

**Issue by littleyoda** [knarfS/smuview#2]
I tested the master branch against my UT61D Multimeter.

I noticed that the negative axis section is missing.
As you can see in the screenshots the voltage is -13V but the graph starts with 0V.

![ut61d-1](https://user-images.githubusercontent.com/6692041/34442801-ee7d9e3c-ecc4-11e7-9e56-7d49d66159bf.png)
![ut61d-2](https://user-images.githubusercontent.com/6692041/34442803-f2067d8a-ecc4-11e7-8a6f-5ed112d783f7.png)

**Comment by knarfS** [comment]
Bug is fixed with commit 6cd2cf32c
