### ISSUE TITLE
Support "forced detection"

### ISSUE THREAD

**Issue by abraxa** [knarfS/smuview#21]
With

https://sigrok.org/gitweb/?p=libsigrok.git;a=commit;h=d643e6bc3942d7b7149a53b3091034d64eac0ad3
and
https://sigrok.org/gitweb/?p=libsigrok.git;a=commit;h=e37e301e26c1da480e41fa68aef3be4efa5d0345

gsi implemented a generally-usable way to let users override model detection in drivers so that they can test a not-yet-supported model to check if it works. Would be useful if SmuView would support it, too.

Related PV bug is here: https://sigrok.org/bugzilla/show_bug.cgi?id=1590

**Comment by knarfS** [comment]
Supported via command line parameter: https://sigrok.org/wiki/Connection_parameters#Forced_detection
