### ISSUE TITLE
Error using DMM Agilent U1252A

### ISSUE THREAD

**Issue by ekute-dev** [knarfS/smuview#25]
## Bug description
DMM Agilent 1252A connected with USB
driver agilent-dmm selected, correct serial port selected

After initialization, smuview seems to try to get data from a second channel that doesn't exist on this meter causing the meter to bip every second or more.

Smuview is sending the serial command 'CONF? @2' which report '*E' that means serial command not understood
same thing with 'FETC? @2'

## Environment 

SmuView-0.0.4-x86_64.AppImage
Debian 10

## log level 5

sr: [00:00.000000] log: libsigrok loglevel set to 5.
Settings: "/home/clement/.config/sigrok/SmuView.conf" format QSettings::NativeFormat
sr: [00:00.003807] backend: libsigrok 0.6.0-git-8491cf7/4:0:0.
sr: [00:00.006556] backend: Libs: glib 2.48.2 (rt: 2.58.3/5803:3), libzip 1.0.1, libserialport 0.1.1/1:0:1 (rt: 0.1.1/1:0:1), libusb-1.0 1.0.22.11312 API 0x01000104, hidapi 0.8.0-rc1, bluez 5.37, libftdi 1.2.
sr: [00:00.006568] backend: Host: x86_64-pc-linux-gnu, little-endian.
sr: [00:00.006573] backend: SCPI backends: TCP, RPC, serial, USBTMC.
sr: [00:00.006595] backend: Firmware search paths:
sr: [00:00.006608] backend:  - /home/clement/.local/share/sigrok-firmware
sr: [00:00.006612] backend:  - /home/frank/smuview/build/deps/share/sigrok-firmware
sr: [00:00.006618] backend:  - /usr/share/gnome/sigrok-firmware
sr: [00:00.006622] backend:  - /home/clement/.local/share/flatpak/exports/share/sigrok-firmware
sr: [00:00.006627] backend:  - /var/lib/flatpak/exports/share/sigrok-firmware
sr: [00:00.006651] backend:  - /usr/local/share/sigrok-firmware
sr: [00:00.006656] backend:  - /usr/share/sigrok-firmware
sr: [00:00.008143] backend: Sanity-checking all drivers.
sr: [00:00.008161] backend: Sanity-checking all input modules.
sr: [00:00.008166] backend: Sanity-checking all output modules.
sr: [00:00.008174] backend: Sanity-checking all transform modules.
sr: [00:00.154657] hwdriver: Scan found 0 devices (agilent-dmm).
sr: [00:00.155606] hwdriver: Scan found 0 devices (appa-55ii).
sr: [00:00.174944] hwdriver: Scan found 0 devices (arachnid-labs-re-load-pro).
sr: [00:00.175702] hwdriver: Scan found 0 devices (atten-pps3203).
sr: [00:00.176158] hwdriver: Scan found 0 devices (baylibre-acme).
sr: [00:00.184691] hwdriver: Scan found 0 devices (bbcgm-2010).
sr: [00:00.185288] hwdriver: Scan found 0 devices (brymen-bm25x).
sr: [00:00.185809] hwdriver: Scan found 0 devices (brymen-bm857).
sr: [00:00.186113] serial: Opening serial port 'hid/bu86x' (flags 1).
sr: [00:00.186986] hwdriver: Scan found 0 devices (brymen-bm86x).
sr: [00:00.187278] hwdriver: Scan found 0 devices (cem-dt-885x).
sr: [00:00.187551] hwdriver: Scan found 0 devices (center-309).
sr: [00:00.187895] hwdriver: Scan found 0 devices (colead-slm).
sr: [00:00.188404] hwdriver: Scan found 0 devices (conrad-digi-35-cpu).
sr: [00:00.196394] demo: Generating square pattern.
sr: [00:00.196453] demo: Generating sine pattern.
sr: [00:00.196628] demo: Generating triangle pattern.
sr: [00:00.196774] demo: Generating sawtooth pattern.
sr: [00:00.196847] hwdriver: Scan found 1 devices (demo).
sr: [00:00.198914] hwdriver: Scan found 0 devices (deree-de5000).
sr: [00:00.199286] hwdriver: Scan found 0 devices (digitek-dt4000zc).
sr: [00:00.199598] hwdriver: Scan found 0 devices (eevblog-121gw).
sr: [00:00.206168] hwdriver: Scan found 0 devices (fluke-45).
sr: [00:00.206546] hwdriver: Scan found 0 devices (fluke-dmm).
sr: [00:00.206888] hwdriver: Scan found 0 devices (gmc-mh-1x-2x-rs232).
sr: [00:00.207053] hwdriver: Scan found 0 devices (gmc-mh-2x-bd232).
sr: [00:00.207199] hwdriver: Scan found 0 devices (gwinstek-gpd).
sr: [00:00.212101] hwdriver: Scan found 0 devices (hp-3457a).
sr: [00:00.235398] hwdriver: Scan found 0 devices (hpib-pps).
sr: [00:00.237173] hwdriver: Scan found 0 devices (iso-tech-idm103n).
sr: [00:00.239921] hwdriver: Scan found 0 devices (kecheng-kc-330b).
sr: [00:00.240685] hwdriver: Scan found 0 devices (kern-ew-6200-2nm).
sr: [00:00.241691] hwdriver: Scan found 0 devices (korad-kaxxxxp).
sr: [00:00.246475] hwdriver: Scan found 0 devices (lascar-el-usb).
sr: [00:00.247319] hwdriver: Scan found 0 devices (manson-hcs-3xxx).
sr: [00:00.248193] hwdriver: Scan found 0 devices (mastech-mas345).
sr: [00:00.249240] hwdriver: Scan found 0 devices (mastech-ms2115b).
sr: [00:00.249793] hwdriver: Scan found 0 devices (mastech-ms5308).
sr: [00:00.250423] hwdriver: Scan found 0 devices (mastech-ms6514).
sr: [00:00.250960] hwdriver: Scan found 0 devices (mastech-ms8250b).
sr: [00:00.251629] hwdriver: Scan found 0 devices (mastech-ms8250d).
sr: [00:00.253050] hwdriver: Scan found 0 devices (maynuo-m97).
sr: [00:00.255117] hwdriver: Scan found 0 devices (metex-m3640d).
sr: [00:00.256302] hwdriver: Scan found 0 devices (metex-m3860m).
sr: [00:00.257397] hwdriver: Scan found 0 devices (metex-m4650cr).
sr: [00:00.258199] hwdriver: Scan found 0 devices (metex-me31).
sr: [00:00.259046] hwdriver: Scan found 0 devices (metrix-mx56c).
sr: [00:00.260147] hwdriver: Scan found 0 devices (mic-98581).
sr: [00:00.260925] hwdriver: Scan found 0 devices (mic-98583).
sr: [00:00.261629] hwdriver: Scan found 0 devices (mooshimeter-dmm).
sr: [00:00.262278] serial: No serial device specified.
sr: [00:00.262288] hwdriver: Scan found 0 devices (motech-lps-301).
sr: [00:00.262839] hwdriver: Scan found 0 devices (norma-dmm).
sr: [00:00.263335] hwdriver: Scan found 0 devices (pce-322a).
sr: [00:00.263915] hwdriver: Scan found 0 devices (pce-pce-dm32).
sr: [00:00.264440] hwdriver: Scan found 0 devices (peaktech-2165).
sr: [00:00.265078] hwdriver: Scan found 0 devices (peaktech-2170).
sr: [00:00.265639] hwdriver: Scan found 0 devices (peaktech-3330).
sr: [00:00.266206] hwdriver: Scan found 0 devices (peaktech-3410).
sr: [00:00.266792] hwdriver: Scan found 0 devices (peaktech-3415).
sr: [00:00.267292] hwdriver: Scan found 0 devices (peaktech-4370).
sr: [00:00.267805] hwdriver: Scan found 0 devices (peaktech-4390a).
sr: [00:00.268315] hwdriver: Scan found 0 devices (radioshack-22-168).
sr: [00:00.268811] hwdriver: Scan found 0 devices (radioshack-22-805).
sr: [00:00.269626] hwdriver: Scan found 0 devices (radioshack-22-812).
sr: [00:00.270248] hwdriver: Scan found 0 devices (rdtech-dps).
sr: [00:00.273377] hwdriver: Scan found 0 devices (scpi-dmm).
sr: [00:00.279411] hwdriver: Scan found 0 devices (scpi-pps).
sr: [00:00.282477] hwdriver: Scan found 0 devices (siemens-b102x).
sr: [00:00.283225] hwdriver: Scan found 0 devices (sparkfun-70c).
sr: [00:00.283990] hwdriver: Scan found 0 devices (tecpel-dmm-8061).
sr: [00:00.284705] hwdriver: Scan found 0 devices (tecpel-dmm-8061-ser).
sr: [00:00.287322] hwdriver: Scan found 0 devices (tekpower-tp4000ZC).
sr: [00:00.288084] hwdriver: Scan found 0 devices (teleinfo).
sr: [00:00.289473] hwdriver: Scan found 0 devices (tenma-72-7730).
sr: [00:00.290243] hwdriver: Scan found 0 devices (tenma-72-7730-ser).
sr: [00:00.290934] hwdriver: Scan found 0 devices (tenma-72-7732).
sr: [00:00.291793] hwdriver: Scan found 0 devices (tenma-72-7732-ser).
sr: [00:00.292640] hwdriver: Scan found 0 devices (tenma-72-7745).
sr: [00:00.293485] hwdriver: Scan found 0 devices (tenma-72-7745-ser).
sr: [00:00.294322] hwdriver: Scan found 0 devices (tenma-72-7750).
sr: [00:00.295142] hwdriver: Scan found 0 devices (tenma-72-7750-ser).
sr: [00:00.295958] hwdriver: Scan found 0 devices (tenma-72-9380a).
sr: [00:00.296732] hwdriver: Scan found 0 devices (tenma-72-9380a-ser).
sr: [00:00.297755] hwdriver: Scan found 0 devices (testo).
sr: [00:00.298595] hwdriver: Scan found 0 devices (tondaj-sl-814).
sr: [00:00.299732] hwdriver: Scan found 0 devices (uni-t-ut32x).
sr: [00:00.300521] hwdriver: Scan found 0 devices (uni-t-ut372).
sr: [00:00.301335] hwdriver: Scan found 0 devices (uni-t-ut60a).
sr: [00:00.302024] hwdriver: Scan found 0 devices (uni-t-ut60a-ser).
sr: [00:00.302972] hwdriver: Scan found 0 devices (uni-t-ut60e).
sr: [00:00.303538] hwdriver: Scan found 0 devices (uni-t-ut60e-ser).
sr: [00:00.304102] hwdriver: Scan found 0 devices (uni-t-ut60g).
sr: [00:00.304754] hwdriver: Scan found 0 devices (uni-t-ut60g-ser).
sr: [00:00.305448] hwdriver: Scan found 0 devices (uni-t-ut612).
sr: [00:00.305957] hwdriver: Scan found 0 devices (uni-t-ut61b).
sr: [00:00.306565] hwdriver: Scan found 0 devices (uni-t-ut61b-ser).
sr: [00:00.307112] hwdriver: Scan found 0 devices (uni-t-ut61c).
sr: [00:00.307615] hwdriver: Scan found 0 devices (uni-t-ut61c-ser).
sr: [00:00.308131] hwdriver: Scan found 0 devices (uni-t-ut61d).
sr: [00:00.308634] hwdriver: Scan found 0 devices (uni-t-ut61d-ser).
sr: [00:00.309136] hwdriver: Scan found 0 devices (uni-t-ut61e).
sr: [00:00.309654] hwdriver: Scan found 0 devices (uni-t-ut61e-ser).
sr: [00:00.310191] hwdriver: Scan found 0 devices (uni-t-ut71a).
sr: [00:00.310924] hwdriver: Scan found 0 devices (uni-t-ut71a-ser).
sr: [00:00.311761] hwdriver: Scan found 0 devices (uni-t-ut71b).
sr: [00:00.312564] hwdriver: Scan found 0 devices (uni-t-ut71b-ser).
sr: [00:00.313159] hwdriver: Scan found 0 devices (uni-t-ut71c).
sr: [00:00.314004] hwdriver: Scan found 0 devices (uni-t-ut71c-ser).
sr: [00:00.314801] hwdriver: Scan found 0 devices (uni-t-ut71d).
sr: [00:00.319715] hwdriver: Scan found 0 devices (uni-t-ut71d-ser).
sr: [00:00.320843] hwdriver: Scan found 0 devices (uni-t-ut71e).
sr: [00:00.321796] hwdriver: Scan found 0 devices (uni-t-ut71e-ser).
sr: [00:00.322674] hwdriver: Scan found 0 devices (va-va18b).
sr: [00:00.323579] hwdriver: Scan found 0 devices (va-va40b).
sr: [00:00.324365] hwdriver: Scan found 0 devices (velleman-dvm4100).
sr: [00:00.325344] serial: Opening serial port 'hid/victor' (flags 1).
sr: [00:00.325808] hwdriver: Scan found 0 devices (victor-dmm).
sr: [00:00.326724] hwdriver: Scan found 0 devices (voltcraft-4080).
sr: [00:00.327569] hwdriver: Scan found 0 devices (voltcraft-k204).
sr: [00:00.328685] hwdriver: Scan found 0 devices (voltcraft-m3650cr).
sr: [00:00.329885] hwdriver: Scan found 0 devices (voltcraft-m3650d).
sr: [00:00.333166] hwdriver: Scan found 0 devices (voltcraft-m4650cr).
sr: [00:00.334829] hwdriver: Scan found 0 devices (voltcraft-me42).
sr: [00:00.337139] hwdriver: Scan found 0 devices (voltcraft-vc820).
sr: [00:00.338542] hwdriver: Scan found 0 devices (voltcraft-vc820-ser).
sr: [00:00.339713] hwdriver: Scan found 0 devices (voltcraft-vc830).
sr: [00:00.340824] hwdriver: Scan found 0 devices (voltcraft-vc830-ser).
sr: [00:00.341958] hwdriver: Scan found 0 devices (voltcraft-vc840).
sr: [00:00.343116] hwdriver: Scan found 0 devices (voltcraft-vc840-ser).
sr: [00:00.344276] hwdriver: Scan found 0 devices (voltcraft-vc870).
sr: [00:00.345441] hwdriver: Scan found 0 devices (voltcraft-vc870-ser).
sr: [00:00.346534] hwdriver: Scan found 0 devices (voltcraft-vc920).
sr: [00:00.347703] hwdriver: Scan found 0 devices (voltcraft-vc920-ser).
sr: [00:00.348891] hwdriver: Scan found 0 devices (voltcraft-vc940).
sr: [00:00.349862] hwdriver: Scan found 0 devices (voltcraft-vc940-ser).
sr: [00:00.350895] hwdriver: Scan found 0 devices (voltcraft-vc96).
sr: [00:00.351871] hwdriver: Scan found 0 devices (voltcraft-vc960).
sr: [00:00.355425] hwdriver: Scan found 0 devices (voltcraft-vc960-ser).
sr: [00:00.357068] hwdriver: Scan found 0 devices (zketech-ebd-usb).
sr: [00:28.986286] bt-bluez: BLE scan (BT)
sr: [00:28.986304] bt-bluez: BLE open
sr: [00:28.986350] bt-bluez: devid failed
sr: [00:28.986359] bt-bluez: BLE scan (LE)
sr: [00:28.986365] bt-bluez: BLE open
sr: [00:28.986383] bt-bluez: devid failed
sr: [00:28.986392] bt-bluez: BLE close
sr: [00:31.583766] hwdriver: Scan found 0 devices (agilent-dmm).
sr: [00:35.847692] hwdriver: sr_config_list(): key 2147418112 (NULL) sdi (nil) cg NULL -> [uint32 20000, 20001]
sr: [00:35.847762] serial: Opening serial port '/dev/ttyUSB0' (flags 1).
sr: [00:35.849542] serial: Parsing parameters from "9600/8n1".
sr: [00:35.849663] serial: Setting serial parameters on port /dev/ttyUSB0.
sr: [00:35.849975] serial: DBG: serial_set_params() rate 9600, 8n1
sr: [00:35.850038] serial: Flushing serial port /dev/ttyUSB0.
sr: [00:35.850115] serial: Wrote 7/7 bytes.
sr: [00:35.917142] serial: Read 1/1 bytes.
sr: [00:35.933153] serial: Read 1/1 bytes.
sr: [00:35.933212] serial: Read 1/1 bytes.
sr: [00:35.933227] serial: Read 1/1 bytes.
sr: [00:35.933239] serial: Read 1/1 bytes.
sr: [00:35.933258] serial: Read 1/1 bytes.
sr: [00:35.933277] serial: Read 1/1 bytes.
sr: [00:35.933309] serial: Read 1/1 bytes.
sr: [00:35.933335] serial: Read 1/1 bytes.
sr: [00:35.933368] serial: Read 1/1 bytes.
sr: [00:35.933392] serial: Read 1/1 bytes.
sr: [00:35.933409] serial: Read 1/1 bytes.
sr: [00:35.933425] serial: Read 1/1 bytes.
sr: [00:35.949138] serial: Read 1/1 bytes.
sr: [00:35.949189] serial: Read 1/1 bytes.
sr: [00:35.949204] serial: Read 1/1 bytes.
sr: [00:35.949222] serial: Read 1/1 bytes.
sr: [00:35.949240] serial: Read 1/1 bytes.
sr: [00:35.949261] serial: Read 1/1 bytes.
sr: [00:35.949278] serial: Read 1/1 bytes.
sr: [00:35.965179] serial: Read 1/1 bytes.
sr: [00:35.965253] serial: Read 1/1 bytes.
sr: [00:35.965281] serial: Read 1/1 bytes.
sr: [00:35.965308] serial: Read 1/1 bytes.
sr: [00:35.965321] serial: Read 1/1 bytes.
sr: [00:35.965346] serial: Read 1/1 bytes.
sr: [00:35.965363] serial: Read 1/1 bytes.
sr: [00:35.965389] serial: Read 1/1 bytes.
sr: [00:35.965406] serial: Read 1/1 bytes.
sr: [00:35.965426] serial: Read 1/1 bytes.
sr: [00:35.965445] serial: Read 1/1 bytes.
sr: [00:35.965463] serial: Read 1/1 bytes.
sr: [00:35.965482] serial: Read 1/1 bytes.
sr: [00:35.981101] serial: Read 1/1 bytes.
sr: [00:35.981166] serial: Read 1/1 bytes.
sr: [00:35.981189] serial: Read 1/1 bytes.
sr: [00:35.981217] serial: Read 1/1 bytes.
sr: [00:35.981244] serial: Read 1/1 bytes.
sr: [00:35.981322] serial: Read 1/1 bytes.
sr: [00:35.981355] serial: Read 1/1 bytes.
sr: [00:35.981381] serial: Read 1/1 bytes.
sr: [00:35.997113] serial: Read 1/1 bytes.
sr: [00:35.997167] serial: Read 1/1 bytes.
sr: [00:35.997181] serial: Read 1/1 bytes.
sr: [00:35.997193] serial: Read 1/1 bytes.
sr: [00:35.997207] serial: Received 44: 'Agilent Technologies,U1252A,TW47450052,V0.91'.
sr: [00:35.997264] serial: Closing serial port /dev/ttyUSB0.
sr: [00:35.998272] hwdriver: Scan found 1 devices (agilent-dmm).
sr: [01:15.716254] device: agilent-dmm: Opening device instance.
sr: [01:15.716296] serial: Opening serial port '/dev/ttyUSB0' (flags 1).
sr: [01:15.717661] serial: Parsing parameters from "9600/8n1".
sr: [01:15.717741] serial: Setting serial parameters on port /dev/ttyUSB0.
sr: [01:15.717985] serial: DBG: serial_set_params() rate 9600, 8n1
Configurable::init(): Init  "Agilent U1252A"  - key  "Data Source"
sr: [01:15.718318] hwdriver: sr_config_list(): key 40004 (data_source) sdi 0x1ba4e50 cg NULL -> ['Live', 'Log-Hand', 'Log-Trig', 'Log-Auto', 'Log-Export']
Configurable::init(): Init  "Agilent U1252A"  - key  "Samplerate"
sr: [01:15.718482] hwdriver: sr_config_list(): key 30000 (samplerate) sdi 0x1ba4e50 cg NULL -> {'samplerate-steps': <[uint64 1, 20, 1]>}
sr: [01:15.718539] hwdriver: sr_config_get(): key 30000 (samplerate) sdi 0x1ba4e50 cg NULL -> uint64 5
Init channel  "P1" , channel_start_timestamp =  "2020.12.01 19:05:50.007"
Init channel  "P2" , channel_start_timestamp =  "2020.12.01 19:05:50.007"
Init channel  "P3" , channel_start_timestamp =  "2020.12.01 19:05:50.007"
sr: [01:15.719088] session: Creating our own main context.
sr: [01:15.719189] session: Starting.
sr: [01:15.719218] hwdriver: agilent-dmm: Starting acquisition.
sr: [01:15.719273] session: bus: Received SR_DF_HEADER packet.
Start aquisition for  "Agilent U1252A" ,  aquisition_start_timestamp_ =  "2020.12.01 19:05:50.007"
sr: [01:15.729590] agilent-dmm: Sending 'CONF?'.
sr: [01:15.729651] serial: Wrote 8/8 bytes.
sr: [01:15.742059] hwdriver: sr_config_get(): key 30000 (samplerate) sdi 0x1ba4e50 cg NULL -> uint64 5
sr: [01:15.742345] hwdriver: sr_config_get(): key 40004 (data_source) sdi 0x1ba4e50 cg NULL -> 'Live'
sr: [01:15.797844] serial: Read 1/1 bytes.
sr: [01:15.797948] serial: Read 1/1 bytes.
sr: [01:15.797959] serial: Read 1/1 bytes.
sr: [01:15.797970] serial: Read 1/1 bytes.
sr: [01:15.797978] serial: Read 1/1 bytes.
sr: [01:15.813864] serial: Read 1/1 bytes.
sr: [01:15.813921] serial: Read 1/1 bytes.
sr: [01:15.813926] serial: Read 1/1 bytes.
sr: [01:15.813954] serial: Read 1/1 bytes.
sr: [01:15.813958] serial: Read 1/1 bytes.
sr: [01:15.813966] serial: Read 1/1 bytes.
sr: [01:15.813974] serial: Read 1/1 bytes.
sr: [01:15.814004] serial: Read 1/1 bytes.
sr: [01:15.814011] serial: Read 1/1 bytes.
sr: [01:15.814018] serial: Read 1/1 bytes.
sr: [01:15.814024] serial: Read 1/1 bytes.
sr: [01:15.814033] serial: Read 1/1 bytes.
sr: [01:15.829825] serial: Read 1/1 bytes.
sr: [01:15.829844] serial: Read 1/1 bytes.
sr: [01:15.829866] serial: Read 1/1 bytes.
sr: [01:15.829869] serial: Read 1/1 bytes.
sr: [01:15.829872] serial: Read 1/1 bytes.
sr: [01:15.829898] serial: Read 1/1 bytes.
sr: [01:15.829901] serial: Read 1/1 bytes.
sr: [01:15.829908] serial: Read 1/1 bytes.
sr: [01:15.829915] serial: Read 1/1 bytes.
sr: [01:15.829920] serial: Read 1/1 bytes.
sr: [01:15.829927] serial: Read 1/1 bytes.
sr: [01:15.829936] serial: Read 1/1 bytes.
sr: [01:15.829945] serial: Read 1/1 bytes.
sr: [01:15.845872] serial: Read 1/1 bytes.
sr: [01:15.845937] serial: Read 1/1 bytes.
sr: [01:15.845941] serial: Read 1/1 bytes.
sr: [01:15.845947] serial: Read 1/1 bytes.
sr: [01:15.845952] serial: Read 1/1 bytes.
sr: [01:15.845959] serial: Read 1/1 bytes.
sr: [01:15.845967] agilent-dmm: Received '"VOLT +5.000000E+00,+1.000000E-04"'.
sr: [01:15.846022] agilent-dmm: CONF? response '"VOLT +5.000000E+00,+1.000000E-04"'.
sr: [01:15.846082] agilent-dmm: Sending 'CONF? @2'.
sr: [01:15.846101] serial: Wrote 11/11 bytes.
sr: [01:15.877812] serial: Read 1/1 bytes.
sr: [01:15.877851] serial: Read 1/1 bytes.
sr: [01:15.877878] serial: Read 1/1 bytes.
sr: [01:15.877882] serial: Read 1/1 bytes.
sr: [01:15.877888] agilent-dmm: Received '*E'.
sr: [01:15.877981] agilent-dmm: Unknown line '*E'.
sr: [01:16.041801] agilent-dmm: Sending 'STAT?'.
sr: [01:16.041893] serial: Wrote 8/8 bytes.
sr: [01:16.069728] serial: Read 1/1 bytes.
sr: [01:16.069793] serial: Read 1/1 bytes.
sr: [01:16.069808] serial: Read 1/1 bytes.
sr: [01:16.069818] serial: Read 1/1 bytes.
sr: [01:16.069834] serial: Read 1/1 bytes.
sr: [01:16.069850] serial: Read 1/1 bytes.
sr: [01:16.069870] serial: Read 1/1 bytes.
sr: [01:16.069885] serial: Read 1/1 bytes.
sr: [01:16.069901] serial: Read 1/1 bytes.
sr: [01:16.086109] serial: Read 1/1 bytes.
sr: [01:16.086189] serial: Read 1/1 bytes.
sr: [01:16.086207] serial: Read 1/1 bytes.
sr: [01:16.086230] serial: Read 1/1 bytes.
sr: [01:16.086258] serial: Read 1/1 bytes.
sr: [01:16.086282] serial: Read 1/1 bytes.
sr: [01:16.086301] serial: Read 1/1 bytes.
sr: [01:16.086318] serial: Read 1/1 bytes.
sr: [01:16.086342] serial: Read 1/1 bytes.
sr: [01:16.086359] serial: Read 1/1 bytes.
sr: [01:16.086379] serial: Read 1/1 bytes.
sr: [01:16.086397] serial: Read 1/1 bytes.
sr: [01:16.101754] serial: Read 1/1 bytes.
sr: [01:16.101799] serial: Read 1/1 bytes.
sr: [01:16.101809] serial: Read 1/1 bytes.
sr: [01:16.101818] serial: Read 1/1 bytes.
sr: [01:16.101825] agilent-dmm: Received '"000001I00F00L00104001"'.
sr: [01:16.101901] agilent-dmm: STAT response '000001I00F00L00104001'.
sr: [01:16.101919] agilent-dmm: Sending 'FETC?'.
sr: [01:16.101977] serial: Wrote 8/8 bytes.
sr: [01:16.133735] serial: Read 1/1 bytes.
sr: [01:16.133776] serial: Read 1/1 bytes.
sr: [01:16.133787] serial: Read 1/1 bytes.
sr: [01:16.133796] serial: Read 1/1 bytes.
sr: [01:16.133805] serial: Read 1/1 bytes.
sr: [01:16.133814] serial: Read 1/1 bytes.
sr: [01:16.133823] serial: Read 1/1 bytes.
sr: [01:16.133838] serial: Read 1/1 bytes.
sr: [01:16.133851] serial: Read 1/1 bytes.
sr: [01:16.133860] serial: Read 1/1 bytes.
sr: [01:16.133872] serial: Read 1/1 bytes.
sr: [01:16.149963] serial: Read 1/1 bytes.
sr: [01:16.181710] serial: Read 1/1 bytes.
sr: [01:16.181760] serial: Read 1/1 bytes.
sr: [01:16.181771] serial: Read 1/1 bytes.
sr: [01:16.181780] serial: Read 1/1 bytes.
sr: [01:16.181790] serial: Read 1/1 bytes.
sr: [01:16.181799] agilent-dmm: Received '+1.00000000E-04'.
sr: [01:16.181881] agilent-dmm: FETC reply '+1.00000000E-04'.
sr: [01:16.181916] session: bus: Received SR_DF_ANALOG packet (1 samples).
sr: [01:16.181997] hwdriver: sr_config_get(): key 30000 (samplerate) sdi 0x1ba4e50 cg NULL -> uint64 5
Init analog base signal  "P1 [V DC]"
Init analog time signal  "P1 [V DC]" , signal_start_timestamp_ =  "2020.12.01 19:05:50.007"
HardwareChannel::push_sample_sr_analog():  "P1"  - No signal found:  "P1 [V DC]"
sr: [01:16.182369] agilent-dmm: Sending 'FETC? @2'.
sr: [01:16.182438] serial: Wrote 11/11 bytes.
sr: [01:16.213576] serial: Read 1/1 bytes.
sr: [01:16.213609] serial: Read 1/1 bytes.
sr: [01:16.213619] serial: Read 1/1 bytes.
sr: [01:16.213629] serial: Read 1/1 bytes.
sr: [01:16.213636] agilent-dmm: Received '*E'.
sr: [01:16.213788] agilent-dmm: Unknown line '*E'.
sr: [01:16.406143] agilent-dmm: Sending 'FETC? @2'.
sr: [01:16.406207] serial: Wrote 11/11 bytes.
sr: [01:16.469484] serial: Read 1/1 bytes.
sr: [01:16.469532] serial: Read 1/1 bytes.
sr: [01:16.469542] serial: Read 1/1 bytes.
sr: [01:16.469551] serial: Read 1/1 bytes.
sr: [01:16.469558] agilent-dmm: Received '*E'.
sr: [01:16.469724] agilent-dmm: Unknown line '*E'.
sr: [01:16.715935] agilent-dmm: Sending 'FETC? @2'.
sr: [01:16.716029] serial: Wrote 11/11 bytes.
sr: [01:16.741400] serial: Read 1/1 bytes.
sr: [01:16.741450] serial: Read 1/1 bytes.
sr: [01:16.741461] serial: Read 1/1 bytes.
sr: [01:16.741472] serial: Read 1/1 bytes.
sr: [01:16.741480] agilent-dmm: Received '*E'.
sr: [01:16.741679] agilent-dmm: Unknown line '*E'.
sr: [01:17.017345] agilent-dmm: Sending 'FETC? @2'.
sr: [01:17.017403] serial: Wrote 11/11 bytes.
sr: [01:17.045230] serial: Read 1/1 bytes.
sr: [01:17.045274] serial: Read 1/1 bytes.
sr: [01:17.045284] serial: Read 1/1 bytes.
sr: [01:17.045295] serial: Read 1/1 bytes.
sr: [01:17.045302] agilent-dmm: Received '*E'.
sr: [01:17.045468] agilent-dmm: Unknown line '*E'.
sr: [01:17.320340] agilent-dmm: Sending 'FETC? @2'.
sr: [01:17.320407] serial: Wrote 11/11 bytes.
sr: [01:17.380978] serial: Read 1/1 bytes.
sr: [01:17.381021] serial: Read 1/1 bytes.
sr: [01:17.381031] serial: Read 1/1 bytes.
sr: [01:17.396856] serial: Read 1/1 bytes.
sr: [01:17.396904] agilent-dmm: Received '*E'.
sr: [01:17.397111] agilent-dmm: Unknown line '*E'.
sr: [01:17.621587] agilent-dmm: Sending 'FETC? @2'.
sr: [01:17.621658] serial: Wrote 11/11 bytes.
sr: [01:17.668767] serial: Read 1/1 bytes.
sr: [01:17.668822] serial: Read 1/1 bytes.
sr: [01:17.668841] serial: Read 1/1 bytes.
sr: [01:17.668856] serial: Read 1/1 bytes.
sr: [01:17.668864] agilent-dmm: Received '*E'.
sr: [01:17.669058] agilent-dmm: Unknown line '*E'.
sr: [01:17.923037] agilent-dmm: Sending 'FETC? @2'.
sr: [01:17.923106] serial: Wrote 11/11 bytes.
sr: [01:17.956574] serial: Read 1/1 bytes.
sr: [01:17.956632] serial: Read 1/1 bytes.
sr: [01:17.956659] serial: Read 1/1 bytes.
sr: [01:17.956675] serial: Read 1/1 bytes.
sr: [01:17.956689] agilent-dmm: Received '*E'.
sr: [01:17.956893] agilent-dmm: Unknown line '*E'.
sr: [01:18.224008] agilent-dmm: Sending 'FETC? @2'.
sr: [01:18.224104] serial: Wrote 11/11 bytes.
sr: [01:18.244292] serial: Read 1/1 bytes.
sr: [01:18.244345] serial: Read 1/1 bytes.
sr: [01:18.260354] serial: Read 1/1 bytes.
sr: [01:18.260400] serial: Read 1/1 bytes.
sr: [01:18.260409] agilent-dmm: Received '*E'.
sr: [01:18.260574] agilent-dmm: Unknown line '*E'.
sr: [01:18.526338] agilent-dmm: Sending 'FETC? @2'.
sr: [01:18.526383] serial: Wrote 11/11 bytes.
...

**Comment by knarfS** [comment]
That looks like a bug in the sigrok driver for the U1252A DMM. In the [driver](https://sigrok.org/gitweb/?p=libsigrok.git;a=blob;f=src/hardware/agilent-dmm/api.c), the U1252A is configured to have 3 channels, but something is wrong when the 2nd channel is selected by the driver (`FETC? @2`).

Unfortunately I couldn't find a protocol documentation (beside the [documentation from the sigrok wiki](https://sigrok.org/wiki/Agilent_U12xxx_series)) and therefore can't say anything about what exactly is wrong.

Maybe you can debug that further and submit a fix to sigrok?

**Comment by ekute-dev** [comment]
You right,

I have to investigate further, it seems the 3 channels are due to this commit : https://github.com/sigrokproject/libsigrok/commit/d822726dbffea1fabe47bcea3e434eadcfa29b31#diff-fac17aaf75e51c33df1b0cf3405e2e9b94476fe59b83a0c7473aae2df5eb0cc5
