### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by ric96** [knarfS/smuview#28]
Fails to build with:
https://paste.ubuntu.com/p/DyNDCdbTMp/

**To Reproduce**
1. Build as described here: [https://sigrok.org/wiki/SmuView](url)

**Expected behavior**
Builds.

**Enviroment (please complete the following information):**
 - SmuView version / git commit: fbb0caf92fb4d5f468e455a7a2725947ffdb4268
 - OS: Fedora 33

**Comment by knarfS** [comment]
You also need to build a recent version of libsigrok to successfully build SmuView (see https://sigrok.org/wiki/Linux#libsigrok). Right now, SmuView is using some cutting edge feature of libsigrok and thous needs an up to date libsigrok.
Unfortunately I don't know how to check for a libsigrok version by its git commit hash in CMake.
