### ISSUE TITLE
USB scan fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by jakobbraun** [knarfS/smuview#31]
**Describe the bug**

I'm trying to discover my UNI_T UT71B using `SmuView-0.0.5-x86_64.AppImage`  but it does not show my USB device. However, if I specify the device via `--driver=uni-t-ut71b:conn=1a86.e008` everything works fine.

**To Reproduce**
1. Open smuview
1. Click on add device button
1. Choose `UNI_T UT71B (uni-t ut71b)` driver
1. select USB
1. Click on `Scan for devices using driver above`
**Expected behavior**
My device shows up in the list

**Screenshots or log**
![image](https://user-images.githubusercontent.com/18247545/121798613-a3dea380-cc27-11eb-8286-2b51d16205c9.png)

[command line output of `./SmuView-0.0.5-x86_64.AppImage -l5`](https://github.com/knarfS/smuview/files/6643434/log.txt)

**Enviroment:**
 - SmuView-0.0.5-x86_64.AppImage
 - Ubuntu 20.04

**Additional Information**
- I did also try to it from a root shell top check if it's a permission problem, but i showed the same behavior.

**Comment by knarfS** [comment]
Unfortunately, the auto scan feature doesn't work with the [UT-D04 cable/adapter](https://sigrok.org/wiki/Device_cables#UNI-T_UT-D04) you are using: There is AFAIK no save way do auto detect the Uni-t DMMs and all the adapter combinations. See https://github.com/sigrokproject/libsigrok/blob/master/README.devices#L305.

Therefor you have to specify your device driver and the USB-ID via the SmuView `-d` parameter or in the connection dialog. In the connection dialog you have to select "Serial Port" and enter (or select?) the USB-ID `1a86.e008` there.
