### ISSUE TITLE
Resolution issue creating new device

### ISSUE THREAD

**Issue by Wurstnase** [knarfS/smuview#8]
Hi,

when open a new device, in my case the Korad, the first page looks like:
![Screenshot at 2019-03-31 21-47-28](https://user-images.githubusercontent.com/8709415/55294142-a1088700-53fe-11e9-84d6-25b0c4827ba5.png)

I can't scroll. Only option is to unpin the frames and put them in again as the complete page.
![Screenshot at 2019-03-31 21-49-51](https://user-images.githubusercontent.com/8709415/55294184-09576880-53ff-11e9-887b-ef5efdffb3b2.png)
![Screenshot at 2019-03-31 21-50-04](https://user-images.githubusercontent.com/8709415/55294186-0eb4b300-53ff-11e9-8289-38d7c073d809.png)

```
# xdpyinfo | grep dimensions 
  dimensions:    1366x768 pixels (361x203 millimeters)
```

**Comment by knarfS** [comment]
I'll close this one, as with SmuView 0.0.5 your views, their size and position as saved as settings. Now you can customizing the views for a device for best fit.
